apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-vol-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-vol-test
  template:
    metadata:
      labels:
        app: example-vol-test
    spec:
      containers:
      - name: volume-test
        image: busybox:1.35
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |
          while echo "$(date) - $(hostname)" >> /test/test.log; do
            tail -n 5 /test/test.log
            sleep 5;
          done;
        volumeMounts:
          - mountPath: /test
            name: example-vol-nfs-pvc
      volumes:
        - name: example-vol-nfs-pvc
          persistentVolumeClaim:
            claimName: example-vol-nfs-pvc

