apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rwmvolumes.dganochenko.work
  labels:
    app: rwmvolume-operator
spec:
 group: dganochenko.work
 names:
   plural: rwmvolumes
   singular: rwm-volume
   kind: RWMVolume
   shortNames:
   - rwmv
 scope: Namespaced
 versions:
   - name: v1alpha1
     served: true
     storage: true
     schema:
       openAPIV3Schema:
         description: "A RWMVolume resource should be created to NFS-Server and related Volume."
         type: object
         properties:
           spec:
             type: object
             properties:
               storageClassName:
                 description: "StorageClass for RWO Volume"
                 type: string
               reclaimPolicy:
                 description: "ReclaimPolicy for RWO Volume, Delete by default"
                 type: string
                 enum:
                 - Delete
                 - Retain
               capacity:
                 description: "Volume capacity"
                 type: integer
                 minimum: 1
             required: ["storageClassName", "capacity"]
         required: ["spec"]
