---
apiVersion: v1
kind: Namespace
metadata:
  name: rwmvolume-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rwmvolume-operator-sa
  namespace: rwmvolume-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rwmvolume-operator-role
rules:
  - apiGroups:
      - dganochenko.work
    resources:
      - rwmvolumes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - dganochenko.work
    resources:
      - rwmvolumes/status
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    verbs:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rwmvolume-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rwmvolume-operator-role
subjects:
  - kind: ServiceAccount
    name: rwmvolume-operator-sa
    namespace: rwmvolume-operator

