apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rwmvolume-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rwmvolume-operator-role
subjects:
  - kind: ServiceAccount
    name: rwmvolume-operator-sa
    namespace: rwmvolume-operator
